Fix clap's semver beta.4 disaster
dfinity/cdk-rs pull request #124
Opened 2021-08-16 20:34 UTC by seniorjoinu

Clap did update their APIs during beta, so `cdk-optimizer` does not build anymore.

This PR fixes it.

2021-08-16 20:34 UTC, seniorjoinu commented on src/ic-cdk-optimizer/src/main.rs
> +        .unwrap();
It is safe to unwrap, since you pass options from "passes" module.

2021-08-16 20:50 UTC, chenyan-dfinity approved these changes

2021-08-16 21:58 UTC, seniorjoinu commented
How do I make it pass?

2021-08-25 16:28 UTC, ericswanson-dfinity requested changes
When I try `cargo build` (toolchain 1.52.1) on this fork, I get the following errors, which are the same errors we have been seeing elsewhere with `clap-3.0.0-beta.4`:

```
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /Users/ericswanson/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling toml v0.5.8
error[E0658]: use of unstable library feature 'osstring_ascii'
   --> /Users/ericswanson/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/parse/matches/matched_arg.rs:130:19
    |
130 |                 v.eq_ignore_ascii_case(val)
    |                   ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #70516 <https://github.com/rust-lang/rust/issues/70516> for more information

error: aborting due to 2 previous errors

```

2021-09-17 17:53 UTC, lwshang commented
As can be seen in this commit (https://github.com/clap-rs/clap/commit/6994be4f1529ba3c6a530473111ba38a7a15b5ce#commitcomment-54999522) which introduce the line `#![doc = include_str!("../README.md")]`.

`clap` changed its minimum supported rust version (msrv) to 1.54. That's why we see the compilation error with rust toolchain 1.52.1.

Such issue exists in several other repos. We do need a clear msrv strategy for our repos. And when msrv is updated to >=1.54, we will be able to upgrade clap as this PR suggest.

2022-02-17 21:11 UTC, adamspofford-dfinity commented
Closing as this was obsoleted by #209.

2022-02-17 21:11 UTC, closed without merging